name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Adjust this if your main branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to deploy branch
        run: |
          cd portfolio/build  # Navigate to the build directory
          git init
          git config --global user.name "skeripting"
          git config --global user.email "scripting1337@gmail.com"
          git add .
          git commit -m "Deploy to Hostinger"
          # Use the GitHub token for authentication
          git push --force "https://${{ secrets.GH_TOKEN }}@github.com/skeripting/portfolio-website.git" deploy
